# 用于演示环境的配置文件
uc:
  jwt:
    # 认证中心服务地址
    acUrlPrefix: http://192.168.59.117:30040/ac/
    # 用户中心后端服务地址
    ucPrefixUrl: http://192.168.59.117:30041/uc
    # 此demo服务地址
    demoServerUrl: http://192.168.59.117:30043/jwt-demo/login
    # 应用在用户中心注册的appKey
    appKey: acc18f82045b4c6ea649978ad671e720
    # 应用在用户中心注册的appSecret
    appSecret: 81067e5b4d3e44c4bebb76f87f7309d5