#工程访问配置
server:
  port: 8811
  servlet:
    context-path: /jwt-demo

#spring环境配置
spring:
  profiles:
    # 运行环境 dev|test|prod,根据active动态加载application-active.yml配置文件
    active: dev
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/vue/
    suffix: .html

